### ISSUE TITLE
Could not find HTML asset

### ISSUE THREAD

**Issue by creage** [GoogleChromeLabs/critters#5]
Followed usage instructions, and get this error:
```
Error: Could not find HTML asset.
    at C:\TFS\WorkZone\WZC\Main\Source\client\node_modules\critters-webpack-plugin\dist\critters.js:200:39
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\TFS\WorkZone\WZC\Main\Source\client\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\TFS\WorkZone\WZC\Main\Source\client\node_modules\tapable\lib\Hook.js:35:21)
    at hooks.optimizeChunkAssets.callAsync.err (C:\TFS\WorkZone\WZC\Main\Source\client\node_modules\webpack\lib\Compilation.js:976:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\TFS\WorkZone\WZC\Main\Source\client\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\TFS\WorkZone\WZC\Main\Source\client\node_modules\tapable\lib\Hook.js:35:21)
    at hooks.additionalAssets.callAsync.err (C:\TFS\WorkZone\WZC\Main\Source\client\node_modules\webpack\lib\Compilation.js:971:36)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\TFS\WorkZone\WZC\Main\Source\client\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\TFS\WorkZone\WZC\Main\Source\client\node_modules\tapable\lib\Hook.js:35:21)
    at hooks.optimizeTree.callAsync.err (C:\TFS\WorkZone\WZC\Main\Source\client\node_modules\webpack\lib\Compilation.js:967:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\TFS\WorkZone\WZC\Main\Source\client\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\TFS\WorkZone\WZC\Main\Source\client\node_modules\tapable\lib\Hook.js:35:21)
    at Compilation.seal (C:\TFS\WorkZone\WZC\Main\Source\client\node_modules\webpack\lib\Compilation.js:904:27)
    at hooks.make.callAsync.err (C:\TFS\WorkZone\WZC\Main\Source\client\node_modules\webpack\lib\Compiler.js:494:17)
    at _done (eval at create (C:\TFS\WorkZone\WZC\Main\Source\client\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:9:1)
    at _err1 (eval at create (C:\TFS\WorkZone\WZC\Main\Source\client\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:32:22)
    at _addModuleChain (C:\TFS\WorkZone\WZC\Main\Source\client\node_modules\webpack\lib\Compilation.js:770:12)
    at processModuleDependencies.err (C:\TFS\WorkZone\WZC\Main\Source\client\node_modules\webpack\lib\Compilation.js:709:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```
Tried with ```html-webpack-plugin``` on
webpack 4.10.2
nodejs 10.3.0

**Comment by stevenfitzpatrick** [comment]
+1

**Comment by lineldcosta** [comment]
+1

**Comment by developit** [comment]
Can someone share their `HtmlWebpackPlugin()` plugin configuration?

**Comment by ikhudo** [comment]
+1

**Comment by creage** [comment]
@developit it is very simple
```javascript
new HtmlWebpackPlugin({
    filename: 'index.html',
    template: '../index.html',
    chunksSortMode: 'none'
})
```
and ``index.html`` has just ``<head>`` and ``<body>`` tags in it.

**Comment by prateekbh** [comment]
What worked for me was the order of plugins in the plugins array. Putting crittersplugin after htmlwebpackplugin made it work for me

**Comment by harrygreen** [comment]
Moving it after `HtmlWebpackPlugin` worked for me, but then got the more cryptic error: `undefined`

**Comment by prateekbh** [comment]
@harrygreen, any stack Trace? Which version?

**Comment by developit** [comment]
@tmf good catch, that's likely the issue.

**Comment by notnotgabriel** [comment]
+1 I'm having the same issue here

**Comment by ilanbm** [comment]
+1 same here

**Comment by aymenbz** [comment]
+1 same issue

**Comment by ilanbm** [comment]
+1 same issue

**Comment by EthianWong** [comment]
+1 same issue

**Comment by andrispraulitis** [comment]
Does this plugin require html-webpack-plugin?

**Comment by brezzhnev** [comment]
Did anyone fix the issue? I've tried moving it after, using the stable version, nothing worked.

**Comment by szTheory** [comment]
Still running into this bug.

**Comment by lokmanm** [comment]
This bug is still on tried with the latest version.

**Comment by developit** [comment]
Looks like we'll need to make this plugin more specific to html-webpack-plugin as of v4:
https://github.com/jantimon/html-webpack-plugin#afteremit-hook

**Comment by Microflash** [comment]
I'm getting the same error 

```sh
 Could not find HTML asset.
    at E:\web\microflash\node_modules\critters-webpack-plugin\dist\critters.js:168:39
    at AsyncSeriesHook.eval [as callAsync] (eval at create (E:\web\microflash\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at AsyncSeriesHook.lazyCompileHook (E:\web\microflash\node_modules\tapable\lib\Hook.js:154:20)
    at E:\web\microflash\node_modules\webpack\lib\Compilation.js:1414:32
    at AsyncSeriesHook.eval [as callAsync] (eval at create (E:\web\microflash\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (E:\web\microflash\node_modules\tapable\lib\Hook.js:154:20)
    at E:\web\microflash\node_modules\webpack\lib\Compilation.js:1409:36
    at AsyncSeriesHook.eval [as callAsync] (eval at create (E:\web\microflash\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (E:\web\microflash\node_modules\tapable\lib\Hook.js:154:20)
    at E:\web\microflash\node_modules\webpack\lib\Compilation.js:1405:32
    at AsyncSeriesHook.eval [as callAsync] (eval at create (E:\web\microflash\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (E:\web\microflash\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.seal (E:\web\microflash\node_modules\webpack\lib\Compilation.js:1342:27)
    at E:\web\microflash\node_modules\webpack\lib\Compiler.js:675:18
    at E:\web\microflash\node_modules\webpack\lib\Compilation.js:1261:4
    at AsyncSeriesHook.eval [as callAsync] (eval at create (E:\web\microflash\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:29:1)
```

with `html-webpack-plugin@3.2.0` using the [following configuration](https://github.com/gridsome/gridsome/blob/6765782723ae1646a96903eebc15f045df062692/gridsome/lib/webpack/createBaseConfig.js#L218).

```js
{
  minify: true,
  templateContent () {
    return createHTMLRenderer(projectConfig.htmlTemplate)({
      app: '<div id="app"></div>'
    })
  }
}
```

[`createHTMLRenderer`](https://github.com/gridsome/gridsome/blob/master/gridsome/lib/server/createHTMLRenderer.js) is a function to generate the HTML from a template.

**Environment**  
Node: 12.16.3
Webpack: 4.43.0

**Comment by dsacramone** [comment]
@naiyerasif you find a solution? Running into this now too.

**Comment by naiyerasif** [comment]
@dsacramone Unfortunately, this became a showstopper for me and I had to revert back to puppeteer for my use case. There's an open PR #52 against this issue, but not sure if it is going anywhere.

**Comment by dmnsgn** [comment]
I can confirm the following PR https://github.com/GoogleChromeLabs/critters/pull/62/ is fixing this issue for me.

**Comment by CuteShaun** [comment]
+ 1 same

**Comment by hjiog** [comment]
i ran into the same issue ,and my html-webpack-plugin version is 5.5.0
