### ISSUE TITLE
Refactor: additionalStylesheets appears broken

### ISSUE THREAD

**Issue by Swaagie** [GoogleChromeLabs/critters#69]
Using the config property `additionalStylesheets` with the refactor branch, e.g. `critters@0.0.7` will lead to the following error where `document.head` is undefined. 

```
(node:30702) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'appendChild' of undefined
    at /Users/mswaagman/projects/public/next.js/examples/with-linaria/node_modules/critters/dist/critters.js:9955:25
    at Array.forEach (<anonymous>)
    at /Users/mswaagman/projects/public/next.js/examples/with-linaria/node_modules/critters/dist/critters.js:9952:17
```

**Comment by rschristian** [comment]
Can reproduce, seems to be a missing getter is all.
