### ISSUE TITLE
TypeError: Cannot read property 'compilation' of undefined

### ISSUE THREAD

**Issue by JakeHenshall** [GoogleChromeLabs/critters#8]
Hi,

I'm using Laravel Mix

When I add the below code.

```
mix.webpackConfig({
    plugins: [
        new Critters({
            // Outputs: <link rel="preload" onload="this.rel='stylesheet'">
            preload: 'swap',

            // Don't inline critical font-face rules, but preload the font URLs:
            preloadFonts: true
        })
    ],
});
```

I receive this error.

/Users/jakehenshall/Code/Preset/node_modules/webpack/bin/webpack.js:348
                        throw err;
                        ^

TypeError: Cannot read property 'compilation' of undefined
    at Critters.apply (/Users/jakehenshall/Code/Preset/node_modules/critters-webpack-plugin/dist/critters.js:181:20)
    at Compiler.apply (/Users/jakehenshall/Code/Preset/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/Users/jakehenshall/Code/Preset/node_modules/webpack/lib/webpack.js:33:19)
    at processOptions (/Users/jakehenshall/Code/Preset/node_modules/webpack/bin/webpack.js:335:15)
    at yargs.parse (/Users/jakehenshall/Code/Preset/node_modules/webpack/bin/webpack.js:397:2)
    at Object.Yargs.self.parse (/Users/jakehenshall/Code/Preset/node_modules/webpack/node_modules/yargs/yargs.js:533:18)
    at Object.<anonymous> (/Users/jakehenshall/Code/Preset/node_modules/webpack/bin/webpack.js:152:7)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)

Thanks, Jake.

**Comment by Splode** [comment]
Did you find a solution to this?

**Comment by JakeHenshall** [comment]
@Splode No I haven't yet :/

**Comment by kamaladenalhomsi** [comment]
+2 the same issue, any one solved that ?

**Comment by developit** [comment]
The latest versions of Critters should not have this issue since they support both Webpack 3 and 4.
